version: 2

models:
  - name: stg_products
    description: "Cleaned product data"

    columns:
      - name: product_id
        description: "Unique identifier for each product"
        tests:
          - unique
          - not_null

      - name: title
        tests:
          - not_null

      - name: price
        tests:
          - not_null
          - is_greater_than:
              value: 0

      - name: stock
        tests:
          - is_greater_than_or_equal_to:
              value: 0

      - name: category
        tests:
          - not_null

  - name: stg_users
    description: "Cleaned customer data"

    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

      - name: email
        tests:
          - not_null
          - is_valid_email

      - name: age
        tests:
          - is_between:
              min_value: 0
              max_value: 120

  - name: stg_carts
    description: "Cleaned shopping carts"

    columns:
      - name: cart_id
        tests:
          - unique
          - not_null

      - name: customer_id
        tests:
          - relationships:
              to: ref('stg_users')
              field: customer_id

      - name: total
        tests:
          - is_greater_than_or_equal_to_column:
              compare_to_column: discounted_total