version: 2

models:
  - name: stg_products
    description: "Cleaned product data"

    columns:
      - name: product_id
        description: "Unique identifier for each product"

        tests:
          - unique
          - not_null

      - name: title
        tests:
          - not_null

      - name: price
        tests:
          - not_null

  - name: stg_users
    description: "Cleaned customer data"

    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

      - name: email
        tests:
          - not_null

  - name: stg_carts
    description: "Cleaned shopping carts"

    columns:
      - name: cart_id
        tests:
          - unique
          - not_null